// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBEnNYkhDs2zlUGm3tOUuVYMqsNYiziw',
    appId: '1:675413710890:android:6b583e8a99d9cbf3310b53',
    messagingSenderId: '675413710890',
    projectId: 'petcare-1f97b',
    storageBucket: 'petcare-1f97b.firebasestorage.app',
  );

}